In [4]:
import numpy as np

np.random.seed(5)

M = np.random.randint(0, 10, size=(5, 5))
print("Matrix : M")
print(M)
print()

n_rows, n_cols = M.shape
present_row = 0
for col in range(n_cols):
    nonzero_row = present_row
    while nonzero_row < n_rows and M[nonzero_row, col] == 0:
        nonzero_row += 1
    if nonzero_row < n_rows:
        M[present_row], M[nonzero_row] = M[nonzero_row].copy(), M[present_row].copy()
        M[present_row] = M[present_row, col]
        for i in range(present_row + 1, n_rows):
            M[i] -= M[i, col] * M[present_row]
        present_row += 1
print("Row Echelon Form of M:")
print(M)

Matrix : M
[[3 6 6 0 9]
 [8 4 7 0 0]
 [7 1 5 7 0]
 [1 4 6 2 9]
 [9 9 9 1 2]]

Row Echelon Form of M:
[[         3          3          3          3          3]
 [       -20        -20        -20        -20        -20]
 [      -416       -416       -416       -416       -416]
 [      9587       9587       9587       9587       9587]
 [1511079525 1511079525 1511079525 1511079525 1511079525]]
