In [3]:
import numpy as np

S = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0],
              [4, 3, 2, 1, 6],
              [5, 4, 3, 2, 1],
              [9, 8, 7, 6, 5]])

U, Sigma, VT = np.linalg.svd(S)
print("Matrix U:")
print(U)
print()

print("Matrix Sigma:")
print(np.diag(Sigma))
print()

print("Matrix V^T:")
print(VT)
print()

recon_S = U @ np.diag(Sigma) @ VT
print("Is S equal to the product of U, Sigma, and V^T?")
print(np.allclose(S, recon_S))
print()

rank_2_approx = U[:, :2] @ np.diag(Sigma[:2]) @ VT[:2, :]
print("Rank 2 approximation of S:")
print(rank_2_approx)
print()

rank_3_approx = U[:, :3] @ np.diag(Sigma[:3]) @ VT[:3, :]
print("Rank 3 approximation of S:")
print(rank_3_approx)

Matrix U:
[[-0.25034994  0.32995395 -0.78176178  0.45016912 -0.12104375]
 [-0.59333573 -0.63993986 -0.25767711 -0.36256606 -0.20143993]
 [-0.26759758  0.66740283  0.07139887 -0.60427677 -0.33573322]
 [-0.29245431 -0.01838858  0.48482769  0.52114603 -0.63834259]
 [-0.6543238   0.18932166  0.28687164  0.1707338   0.65159213]]

Matrix Sigma:
[[2.42328002e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 7.31682211e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.49838976e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.71568400e-16
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  3.25987873e-16]]

Matrix V^T:
[[-5.04767930e-01 -4.89470893e-01 -4.74173857e-01 -4.58876821e-01
  -2.64988299e-01]
 [ 1.05493629e-01 -5.14490711e-02 -2.08391771e-01 -3.65334472e-01
   8.99626412e-01]
 [ 6.58847806e-01  2.40356481e-01 -1.78134845e-01 -5.96626170e-01
  -3.4706